# Get the detailed printer informations

---
string state
string state_message
string hostname
string config_file
string software_version
string cpu_info
string manufacturer
string model
string location